development:
  adapter: postgresql
  encoding: unicode
  database: project_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: project_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: project_production
  pool: 5
